return {
  keymenu = {
    which_key = true,
    mini_clue = false,
  },
  pde = {
    ai = true,
    angular = false,
    cpp = false,
    csharp = false,
    docker = true,
    elixir = false,
    flutter = false,
    go = false,
    html = true,
    java = false,
    json = true,
    julia = false,
    jupyter = false,
    lua = true,
    python = true,
    r = false,
    react = true,
    ruby = false,
    rust = true,
    solidity = false,
    svelte = false,
    tailwind = true,
    terraform = false,
    typescript = true,
    vuejs = false,
    yaml = true,
  },
}
