return {
  pde = {
    angular = true,
    cpp = true,
    csharp = false,
    go = false,
    html = true,
    java = false,
    json = true,
    julia = true,
    jupyter = true,
    lua = true,
    python = true,
    r = true,
    react = true,
    rust = true,
    solidty = true,
    svelte = true,
    tailwind = true,
    typescript = true,
    vuejs = true,
  },
}
