return {
  pde = {
    ai = true,
    angular = true,
    cpp = true,
    csharp = false,
    elixir = true,
    go = false,
    html = true,
    java = false,
    json = true,
    julia = true,
    jupyter = true,
    lua = true,
    python = true,
    r = true,
    react = true,
    ruby = true,
    rust = true,
    solidity = true,
    svelte = true,
    tailwind = true,
    terraform = true,
    typescript = true,
    vuejs = true,
  },
}
